service:
  name: grs-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  environment:
    APPOINTMENT_TABLE_NAME: ${self:custom.AppointmentTable.name}
  iamRoleStatements:
    - ${file(iam/AppointmentTableIAM.yml):AppointmentTableIAM}
resources:
  Resources:
      AppointmentTable: ${file(resources/AppointmentTable.yml):AppointmentTable}
functions:
  createAppointment:
    handler: src/handlers/createAppointment.handler
    events:
      - http:
          method: POST
          path: /appointment
  getAppointment:
    handler: src/handlers/getAppointment.handler
    events:
      - http:
          method: GET
          path: /appointment/{id}
custom:
  AppointmentTable:
    name: !Ref AppointmentTable
    arn: !GetAtt AppointmentTable.Arn
  bundle:
    linting: false